### PR TITLE
[p5.js - es] Translate Color and Shape reference

### PR DESCRIPTION
**Pull request by ml008008**

### CODE REVIEW

**Review by holomorfo — APPROVED** [review]
Aprobado, muchas gracias Marce (y)

**Comment by Qianqianye** [comment]
Thanks @ml008008! @holomorfo @Guirdo, is this PR approved by both of you?

**Comment by holomorfo** [comment]
hi @Qianqianye, yes, this PR is approved

**Review by Guirdo — APPROVED** [review]
I approve it @Qianqianye @holomorfo

**Comment by Qianqianye** [comment]
Thanks @ml008008  @holomorfo @Guirdo!

**Pull request merged**
