### PR TITLE
(ko) patch several description

### PR DESCRIPTION
**Pull request by ienground**
피드백 반영하여 수정했습니다. 확인 부탁드려요!
line, isConstructor 따옴표 제거
itemtype method / property로 변경
description 오류 등을 수정했습니다.

@yinhwa @designerSejinOH

### CODE REVIEW

**Review by yinhwa — APPROVED** [review]
-- re-approving --

**Comment by limzykenneth** [comment]
@yinhwa Do you still need #87 to be merged?

**Comment by yinhwa** [comment]
Hi @ienground i see 4 MDX files missing on this PR when compared to #87 : displayDensity, getURL, getURLParams, getURLPath.
Could you check in with this and add the 4 files to this PR? You can also close #87 if needed. Thanks!

@limzykenneth I'll ask for merging again after solving this, thanks!

**Comment by ienground** [comment]
@yinhwa @designerSejinOH 
Sorry for that! I checked and add them again.

**Review by yinhwa — APPROVED** [review]
Hi @Qianqianye @limzykenneth we're ready to merge this PR! thank you very much @ienground :) @designerSejinOH

**Comment by Qianqianye** [comment]
Thanks @ienground @designerSejinOH @yinhwa!

**Pull request merged**
